# Entrada de datos  : input()
print('-' * 80)
print('Entrada de datos : input()')
print()

_user_code = input("_user_code = input('Código : ')          = ")
user_name = input("user_name = input('Nombre : ')           = ")
user_lastname = input("user_lastname = input('Apellido : ')     = ")
user_age = input("user_age = input('Edad : ')              = ")
user_height = input("user_height = input('Estatura : ')       = ")
user_blood_gr = input("user_blood_gr = input('Grp sang : ')     = ")
user_blood_tp = input("user_blood_tp = input('Tip sang : ')     = ")
user_is_activate = input("user_is_activate = input('¿Activo? : ')  = ")
print()
print("     print(_user_code)       = ", _user_code)
print("     print(user_name)        = ", user_name)
print("     print(user_lastname)    = ", user_lastname)
print("     print(user_age)         = ", user_age)
print("     print(user_height)      = ", user_height)
print("     print(user_blood_gr)    = ", user_blood_gr)
print("     print(user_blood_tp)    = ", user_blood_tp)
print("     print(user_is_activate) = ", user_is_activate)
print()
print('-' * 80)
print()