# Generated by Django 5.0.1 on 2024-02-28 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commet',
            new_name='comment',
        ),
    ]
